name: CI

on:
  push:
    branches:
    - master

  pull_request:
    branches:
      - "*"

jobs:
  build:
    strategy:
      platform: ubuntu-latest
      node-version: 10.x

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 10
      uses: actions/setup-node@v1
      with:
        node-version: 10
    - run: npm install -g yarn
    - run: yarn bootstrap
    - run: yarn truffle test --network test
